import com.practice.entities.Person;
import com.practice.entities.SaleableItem;



rule "calculate old age eligible discount"
when
  $saleItem : SaleableItem();
  $person:Person (getAgeInYears() > 70);
then
	System.out.println("rule triggered for discount of 20");
	$saleItem.setSaleDiscountPercent(20);
end

rule "calculate mid age eligible discount"
when
  person:Person (getAgeInYears() > 50 && getAgeInYears() < 70);
  $saleItem : SaleableItem();
then
  $saleItem.setSaleDiscountPercent(10);
  System.out.println("rule triggered for discount of 10");
end