import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

public class Solution {

    static boolean flag;
    static int B;
    static int H;

  static {
      try {
           B = Integer.parseInt(new BufferedReader(new InputStreamReader(System.in)).readLine());
           H = Integer.parseInt(new BufferedReader(new InputStreamReader(System.in)).readLine());
          System.out.println("B value is" + B);
          System.out.println("H value is" + H);
          if (B <= 0 || H <= 0) {
              throw new Exception("Breadth and Height must be positive");
          }
          flag = true;
      }  catch (Exception e) {
              System.out.println("java.lang.Exception: Breadth and height must be positive");
          }
  }
  private static boolean assignValues() throws Exception {
          
            B = Integer.parseInt(new BufferedReader(new InputStreamReader(System.in)).readLine());
            H = Integer.parseInt(new BufferedReader(new InputStreamReader(System.in)).readLine());
          
          if (B <= 0 || H <= 0) {
              throw new Exception("Breadth and Height must be positive");
          }
          return true;
      }

public static void main(String[] args){
    if(flag){
      int area=B*H;
      System.out.print(area);
    }
    
  }//end of main

}//end of class

